### ISSUE TITLE
Add options for treeshaking through build-time flags

### ISSUE THREAD

**Issue by mydea** [getsentry/sentry-javascript-bundler-plugins#425]
Based on this https://docs.sentry.io/platforms/javascript/configuration/tree-shaking/, we should add flags to the bundler plugins to automatically shake out code you don't care about, something like:

```js
sentryWebpackPlugin({
  // other options...
  stripDebugStatements: true,
  stripRrwebCanvas: true,
  stripRrwebIframe: true,
  stripRrwebShadowDom: true
});
```

(naming TBD).

```[tasklist]
### Tasks
- [ ] Allow to strip debug statements (`__SENTRY_DEBUG__: false`)
- [ ] Allow to strip rrweb canvas capturing (`__RRWEB_EXCLUDE_CANVAS__`: true)
- [ ] Allow to strip rrweb iframe capturing (`__RRWEB_EXCLUDE_IFRAME__`: true)
- [ ] Allow to strip rrweb shadow dom capturing (`__RRWEB_EXCLUDE_SHADOW_DOM__`: true)
```

**Comment by lforst** [comment]
Bikeshed:
- ~stripDebugStatements~ disableDebugStatements
- ~stripRrwebCanvas~ disableReplayCanvasSupport
- ~stripRrwebIframe~ disableReplayIframeSupport
- ~stripRrwebShadowDom~ disableReplayShadowDomSupport

Reasons:
- We cannot name it "strip" because we cannot control what will be treeshaken. Users can still acces the APIs preventing them from being shaken or they can disable tree shaking in their bundlers.
- We shouldn't name it "rrweb" because it is not well known.

**Comment by mydea** [comment]
After talking a bit about this offline with Luca, let's put this into an object to make it clear what it does, e.g.:

```js
sentryWebpackPlugin({
  // other options...
  bundleSizeOptimizations: {
    excludeDebugStatements: true,
    excludeReplayCanvas: true,
    excludeReplayShadowDom: true,
    excludeReplayIframe: true
  }
});
```

I kind of prefer `exclude` or something like this over `disable`, but not strongly, so 🤷
